version: 2

models: 
  - name: stg_raw__sales
    columns: 
     - name: date_date
       tests:
        - not_null
     - name: product_id
       tests: 
        - not_null
    tests:
      - unique:
          column_name: "date_date"
