version: 2

sources:
  - name: raw
    description: "this is my raw data set, which is called here schema"
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "this is sales table"
        columns:
          - name: date_date
            description: "date of sales"
          - name: orders_id
            description: "order id"
          - name: pdt_id
          - name: revenue
          - name: quantity
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: "this is product table"
        columns:
          - name: products_id
            description: "product id"
            tests:
              - not_null
              - unique
          - name: purchSE_PRICE
      - name: ship
        identifier: raw_gz_ship
        description: "this is ship table"
        columns:
          - name: orders_id
            tests:
              - not_null
              - unique
          - name: shipping_fee
            description: "revenue fee"
          - name: logCost
          - name: ship_cost
      - name: adwords
        identifier: raw_gz_adwords
        description: "this is sadwords data"
        columns:
          - name: date_date
            description: "date"
          - name: paid_source
            description: "paid_source"
          - name: campaign_key
            description: "key of the campaign"
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: "this is bing data"
        columns:
          - name: date_date
            description: "date"
          - name: paid_source
            description: "paid_source"
          - name: campaign_key
            description: "key of the campaign"
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: "this is criteo data"
        columns:
          - name: date_date
            description: "date"
          - name: paid_source
            description: "paid_source"
          - name: campaign_key
            description: "key of the campaign"
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"

      - name: facebook
        identifier: raw_gz_facebook
        description: "this is facebook data"
        columns:
          - name: date_date
            description: "date"
          - name: paid_source
            description: "paid_source"
          - name: campaign_key
            description: "key of the campaign"
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"

models:

  # Intermediate #

  - name: int_orders_margin
    description: margin calculation per order
    columns:
     - name: orders_id
       description: primary key
       tests:
         - unique
         - not_null
     - name: margin
       description: margin = revenue - purchase_cost
       tests:
         - not_null
     - name: Purchase_cost
       description: purchase_cost = quantity * purchase_price
       tests:
         - not_null
     - name: date_date
       description: date of the order
       tests:
         - not_null
     - name: revenue
       description: sum of revenue per order
       tests:
         - not_null
     - name: quantity
       description: sum of quantity per order
       tests:
         - not_null

  - name: int_sales_margin
    description: "margin calculation per order"
    columns:
      - name: orders_id
        description: orders key
        tests:
          - not_null
      - name: products_id
        description: products key
        tests:
           - not_null
      - name: margin
        description: Margin = Revenue - Purchase_cost
        tests:
           - not_null
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
        tests:
           - not_null
      - name: date_date
        description: date of the order
        tests:
           - not_null
      - name: revenue
        description: sum of revenue per order
        tests:
           - not_null
      - name: quantity
        description: sum of quantity per order
        tests:
           - not_null
    tests:
       - unique:
          column_name: "(orders_id || '-' || products_id)"
  - name: int_orders_operational
    description: operational margin calculation per order
    columns:
      - name: orders_id
        description: primary key
        tests:
           - unique
           - not_null
      - name: date_date
        description: date of the order
        tests:
           - not_null
      - name: operational_margin
        description: operational_margin = margin + shipping_fee - logcost - ship_cost
      - name: quantity
        description: sum of quantity per order
        tests:
           - not_null
      - name: revenue
        description: sum of revenue per order
        tests:
           - not_null
      - name: purchase_cost
        description: purchase_cost = quantity * purchase_price
        tests:
           - not_null
      - name: margin
        description: margin = revenue - purchase_cost
        tests:
           - not_null
      - name: shipping_fee
        description: the price the customer pays for shipping
      - name: logcost
        description: the cost of preparing the parcel in the distribution centre/warehouse
      - name: ship_cost
        description: shipping cost paid by Greenweez to the carrier/logistics provider


  - name: int_campaigns
    description: "all campaign data"
    columns:
      - name: date_date
        description: "date"
        tests:
          - not_null
      - name: paid_source
        description: "paid_source"
        tests:
          - not_null
      - name: campaign_key
        description: "key of the campaign"
        tests:
          - not_null
      - name: campaign_name
        tests:
          - not_null
      - name: ads_cost
        tests:
          - not_null
      - name: impression
        tests:
          - not_null
      - name: click
        tests:
          - not_null
    tests:
      - unique:
           column_name: "(date_date || '_' || campaign_key)"

  - name: int_campaigns_day
    description: "all campaign data per day"
    columns:
      - name: date_date
        description: "date"
        tests:
          - not_null
          - unique
      - name: ads_cost
        tests:
          - not_null
      - name: ads_impression
        tests:
          - not_null
      - name: ads_clicks
        tests:
          - not_null